// PROJETO
// É UM CLIENTE CUJO O NOME DA EMPRESA É BITEBANK.
// ESSE CLIENTE DESEJA CADASTRAR CLIENTES E TER CONTAS CORRENTES PARA OS SEUS CLIENTES

// DADOS QUE CADA CLIENTE PRECISA:
// NOME - CPF - SALDO - AGENCIA

//NO JAVASCRIPT NAO TEM O TIPO {private}, OFICIALMENTE PARA UTILIZAR.
//ESTA LIBERADO PARA TESTES O USO DE {#} PARA DIZER QUE É PRIVADO.
//OU É POSSÍVEL SOMENTE INFORMA NO INICIO DA VARIÁVEL O {_} UNDERLINE.

//ATENCAO!!!!!
//CONFIGURANDO A CRICAO DE CLASES NO JAVASCRIPT
//RODAR COMANDO ABAIXO:
//npm init
//SEGUI O FLUXO DE CONFIGURACAO E LOGO EM SEGUIDA SERA CRIADO UM ARQUIVO {package.json}
//ABRIR O ARQUIVO {package.json} E ADICIONAR {,"type": "module"}
//DEPOIS DISSO, POSSO CRIAR AS CLASES EM ARQUIVOS SEPARADOS E ADICIONANDO O {export}
//A CLASE QUE ESTA CHAMANDO, DEVE ADICIONAR O {import {NomeDaClasse} from "caminhoDaClase.js"} E FAZER A INSTANCIA DESSA CLASSE!
//VEJA O EXEMPLO ABAIXO:

//IMPORTANDO A CLASSE CLIENTE:
import { Cliente } from "./Class/Cliente.js";

//INSTANCIANDO A CLASSE CLIENTE
const cliente1 = new Cliente();

//ACESSANDO OS PARAMETROS DA CLASSE E ATRIBUINDO VALORES:
cliente1.nome = "Werike Santos";
cliente1.cpf = "000.222.444.06";

//EXIBINDO OS VALORES ADICIONADOS DENTRO DA CLASSE
console.log(cliente1);
//RETORNO
//Cliente { nome: 'Werike Santos', cpf: '000.222.444.06' }
